services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trading_net

  live_dashboard_backend:
    build: ./live_dashboard_backend
    container_name: live_dashboard_backend
    ports:
      - "8083:8081"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - trading_net

  email_worker:
    build: ./email_worker
    container_name: email_worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - trading_net

  console_alert_worker:
    build: ./console_alert_worker
    container_name: console_alert_worker
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - trading_net

networks:
  trading_net:
    driver: bridge